name: React Frontend CD

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Kill existing serve process (if running)
        run: |
          # PowerShell로 프로세스 확인 및 종료
          $process = Get-Process | Where-Object { $_.ProcessName -eq "serve" }
          if ($process) {
            Write-Host "Killing existing serve process..."
            Stop-Process -Id $process.Id
          } else {
            Write-Host "No existing serve process found."
          }

      - name: Start server using bash in WSL
        run: |
           Start-Process powershell -ArgumentList "npx serve -s build -l 0.0.0.0:3000" -NoNewWindow
          exit 0  # Exit the GitHub Actions session, allowing the server to continue running

      - name: Test server availability (optional)
        run: |
          Invoke-WebRequest -Uri http://localhost:3000
