name: React Frontend CD

on:
  workflow_run:
    workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start server
        run: |
          bash serve -s build -l 3000  # 서버를 3000번 포트에서 실행
