name: React Frontend CD

on:
  workflow_run:
    workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print current working directory
        run: |
          Write-Host "Current working directory: $(pwd)"
          Get-ChildItem -Force  # PowerShell에서 현재 디렉토리의 파일 목록 출력

      - name: Run deploy.sh script using bash
        run: |
          bash ./deploy.sh  # bash로 deploy.sh를 실행
