name: React Frontend CD

on:
  workflow_run:
    workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to local server
        run: |
          bash ./deploy.sh
