name: React Frontend CD

on:
  workflow_run:
    workflows: ['React Frontend CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to local server
      run: ./deploy.sh
